import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users');
  const customers = await response.json();
  return { 
    props: { 
      customers 
    } 
  };
};
 

export default function Home({ customers }) {
  return (
    <>
      <Head>
        <title>Profile Navigator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <h1 className={styles.title}>Customers</h1>
        <section className={styles.grid__wrapper}>
        {
          customers.map(customer => (
            <Link 
              href={`/customers/${customer.id}`}
              key={customer.id}
              className={styles.card}
            >
              <h2 className={styles.card__title}>{customer.name}</h2>
              <p>{customer.email}</p>
              <p>{customer.address.city}</p>
            </Link>
          )) 
        }
        </section>
      </main>
    </>
  )
}

// export async function getServerSideProps() {
//   const response = await fetch('https://jsonplaceholder.typicode.com/users')
//   const customers = await response.json()
//   return {
//     // pass the props you want to pass to your component above
//     props: { customers }
//   }
// }

