import Head from 'next/head'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { HiOutlineMail } from 'react-icons/hi'
import { GoLocation } from 'react-icons/go'
import { ImProfile } from 'react-icons/im'
import { GiClick } from 'react-icons/gi'

const inter = Inter({ subsets: ['latin'] })

export const getStaticProps = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users');
  const customers = await response.json();
  return { 
    props: { 
      customers 
    } 
  };
};
 

export default function Home({ customers }) {
  return (
    <>
      <Head>
        <title>Profile Navigator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav class="navbar  navbar-dark bg-primary fixed-top mb-5">
        <div class="container-fluid">
          <span class="navbar-brand mb-0 h1 fw-bolder">Profile Navigator</span>
        </div>
      </nav>
      <main className={`${inter.className} my-5 px-4`}>
      <h1 className="fw-bold border-bottom border-dark pt-4">Customers</h1>
      <div className="row row-cols-1 row-cols-md-3 g-4 pt-4">
          {
            customers.map(customer => (
              <div className="col-sm-6">
                <div className="card border-secondary text-dark bg-light">
                  <div className="card-body">
                    <h5 className="card-title"><ImProfile /> {customer.name}</h5>
                    <p className="card-text"><HiOutlineMail /> {customer.email}</p>
                    <p className="card-text"><GoLocation /> {customer.address.city}</p>
                    <Link href={`/customers/${customer.id}`} 
                      className="btn btn-primary"
                      key={customer.id}
                    ><GiClick /> Visit Profile</Link>
                  </div>
                </div>
              </div>
            ))
          }
      </div>
      </main>
    </>
  )
}

// export async function getServerSideProps() {
//   const response = await fetch('https://jsonplaceholder.typicode.com/users')
//   const customers = await response.json()
//   return {
//     // pass the props you want to pass to your component above
//     props: { customers }
//   }
// }

