import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ users }) {
  return (
    <>
      <Head>
        <title>Profile Navigator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <h1 className={styles.title}>Customers</h1>
        <section className={styles.grid__wrapper}>
        {
          users.map(user => (
            <div 
              key={user.id}
              className={styles.card}
            >
              <h2 className={styles.card__title}>{user.name}</h2>
            </div>
          )) 
        }
        </section>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const response = await fetch('https://jsonplaceholder.typicode.com/users');
  const data = await response.json();
  return { 
    props: { 
      users: data 
    } 
  };
};
 